name = "subscription-manager"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages Functions 配置
[pages]
# 指定Functions目录
functions_dir = "."

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "subscription-db"
database_id = "7919470b-9966-46d2-8bf2-77421a00897a"

# KV 存储绑定
[[kv_namespaces]]
binding = "subscription"
id = "655eece90d1444269cafdc7bc9397e56"

# 环境变量
[vars]
ENVIRONMENT = "production"