name = "subscription-manager"
main = "_worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Workers 发布所需的最小绑定骨架；id 留空，Actions 会在首次创建后写入临时配置
[[d1_databases]]
binding = "DB"
database_name = "subscription-db"
# database_id 可留空；Actions 首次创建后会写入临时 merged 配置再发布

[[kv_namespaces]]
binding = "subscription"
# id 留空；Actions 首次创建后会写入临时 merged 配置再发布

[vars]
ENVIRONMENT = "production"