name: Deploy to Cloudflare Pages (Optimized)

on:
  push:
    branches: [main]
  workflow_dispatch: # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Validate Environment
        run: |
          echo "🔍 验证环境配置..."
          
          if [ -z "${{ secrets.CLOUDFLARE_API_TOKEN }}" ]; then
            echo "❌ CLOUDFLARE_API_TOKEN 未设置"
            echo "请在 GitHub 仓库设置中添加 CLOUDFLARE_API_TOKEN 密钥"
            exit 1
          fi
          
          if [ -z "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" ]; then
            echo "❌ CLOUDFLARE_ACCOUNT_ID 未设置"
            echo "请在 GitHub 仓库设置中添加 CLOUDFLARE_ACCOUNT_ID 密钥"
            exit 1
          fi
          
          echo "✅ 环境配置验证通过"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Prepare Deployment Artifacts
        run: |
          echo "📦 准备部署产物..."
          
          # 创建部署目录
          mkdir -p public
          
          # 复制必要的文件到部署目录
          cp _worker.js public/
          cp index.html public/
          cp data.js public/
          
          echo "✅ 部署产物已准备完成:"
          echo "   - _worker.js (Cloudflare Functions)"
          echo "   - index.html (静态页面)"
          echo "   - data.js (数据文件)"
          
          # 显示部署目录内容
          echo ""
          echo "📋 部署目录内容:"
          ls -la public/

      - name: Deploy to Cloudflare Pages
        run: |
          echo "🚀 部署到 Cloudflare Pages..."
          
          # 部署到 Cloudflare Pages
          wrangler pages deploy ./public \
            --project-name=cfvless-admin \
            --commit-dirty=true \
            --branch=main
          
          echo "✅ 部署完成！"
          echo "🔗 访问地址: https://cfvless-admin.pages.dev"
          
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Post-Deploy Instructions
        run: |
          echo ""
          echo "🎉 代码部署成功！"
          echo ""
          echo "⚠️  重要提醒：首次部署后需要手动配置资源绑定"
          echo ""
          echo "📋 下一步操作（仅首次需要）："
          echo "1. 前往 Cloudflare Dashboard: https://dash.cloudflare.com"
          echo "2. 进入 Workers 和 Pages → Pages → cfvless-admin"
          echo "3. 点击 设置 → 函数"
          echo "4. 添加以下绑定："
          echo "   📊 D1 数据库绑定:"
          echo "      - 变量名: DB"
          echo "      - D1 数据库: subscription-db"
          echo "   🗄️  KV 命名空间绑定:"
          echo "      - 变量名: subscription"
          echo "      - KV 命名空间: subscription"
          echo "5. 点击保存，Pages 会自动重新部署"
          echo ""
          echo "📖 详细配置指南请参考: DEPLOYMENT_FIX_GUIDE.md"